Descriptions component
Clotonervo/Event-Planner pull request #130
Opened 2020-11-20 03:31 UTC by jam1023

Made the description component. Takes in a descriptions. Puts word description as a title and then the description.
<img width="1305" alt="Screen Shot 2020-11-19 at 7 27 45 PM" src="https://user-images.githubusercontent.com/69694746/99754687-2e05c580-2aa6-11eb-8381-17b44ed330b6.png">

2020-11-20 20:12 UTC, hokansom commented on client/src/components/EventView/Description/index.js
> +    <TextBar>Description</TextBar>
Instead of this TextBar, you can use the <h1>. That will match what we have done in other places.

2020-11-20 20:12 UTC, hokansom commented on client/package.json
> +    "mongodb": "^3.6.3",
We don't need mongodb as a dependency on the frontend, so you can remove this import

2020-11-20 20:15 UTC, hokansom commented on client/src/components/EventView/Description/index.js
> +    <div>{description}</div>
The description text is a little small, maybe set the font size to be fontSize20.

2020-11-20 20:15 UTC, hokansom requested changes
Almost there, just some minor styling tweaks to be consistent with other pages

2020-11-21 15:39 UTC, jam1023 commented
@hokansom 
I made those changes, so I think it should be ready now :)

2020-11-27 17:59 UTC, hokansom approved these changes

2020-11-27 18:11 UTC, merged