Completed Event Header for view page
Clotonervo/Event-Planner pull request #133
Opened 2020-12-02 01:41 UTC by Clotonervo

Let me know what changes need to go into this one 👍 💯 🥇 🔢 💯 👍 🥇 🥇 💯 👍 🔢 💯 💯

2020-12-02 02:47 UTC, hokansom commented on client/src/components/EventView/Header/index.js
> +  onEditTitle: PropTypes.func
This component doesn't need to edit the title, so you can remove this prop

2020-12-02 02:48 UTC, hokansom commented on client/src/components/EventView/Header/index.js
> +          <DateInput
We don't want the date to be editable, so you would want to make your own component to just display the date

2020-12-02 02:52 UTC, hokansom commented on client/src/components/EventView/Header/index.js
> +  width: 60%;
For this component, we wouldn't want to set a width. If the event has a super long title, we would want it to extend to the other margin, and then wrap if necessary.

2020-12-03 18:25 UTC, Clotonervo commented
I believe I fixed those things you mentioned before. I'm pretty rusty with React, so let me know if I did something wrong there haha. The one thing that I wasn't sure was ok is that I changed the `width: 60%` to be just `width: 100%` as I figured that that would just be easier than restructuring the rest of the html structure. If that needs to be changed let me know. Also I had a hard time getting the date to display correctly, so I ended up just using a function on the date object that converted it into a string. I didn't know if this mattered but it wasn't as simple as last time we were using a date picker to display the date rather than doing it ourselves. Let me know what you think!

2020-12-03 23:24 UTC, hokansom commented on client/src/components/EventView/Header/index.js
> +          <DateTextContainer>{realDate.toDateString()}</DateTextContainer>
Josiah created a useful component for formatting dates. It's located in /Common/Date. You can add a new DateFormat to it with whatever format you want, like "MMMM D, YYYY", which would print out December 3, 2020. Let me know if you need more help with that part

2020-12-03 23:24 UTC, hokansom requested changes
Everything looks good,  but we can improve the date display. See my other comment.

2020-12-04 01:21 UTC, hokansom approved these changes
Looks good!

2020-12-04 01:21 UTC, merged