Event cards
Clotonervo/Event-Planner pull request #51
Opened 2020-10-15 20:56 UTC by jam1023

Made EventCard and AddEventCard without inline styling. Both are responsive to change in screen size. EventCard takes in text (name of event) and color (background color of the card).

2020-10-15 22:39 UTC, hokansom commented on client/src/components/Main/EventCard/index.js
> +border-top-left-radius: 7px;
You should use borderRadius from the style-constants here and the other places where you set the border-radius for consistency.

2020-10-15 22:41 UTC, hokansom commented on client/src/components/Main/index.js
> +      {/* <Invitation isUnopened={true}></Invitation>
Can you revert your changes for this file (Main/index.js)? We don't need this code in the master branch since it was just used for development.

2020-10-15 22:42 UTC, hokansom commented on client/src/components/Main/EventCard/index.js
> +bottom: 0;
Can we give this component some padding? That way the text isn't right up to the edge of the card.

2020-10-15 22:43 UTC, hokansom requested changes
Overall great job! There's just a few minor tweaks that I mentioned in the comments.

2020-10-16 00:29 UTC, jam1023 commented
I updated the things mentioned. To revert changes to Main/index.js, I copied the current page and commented out 3 lines which would not allow it to compile because my branch did not have everything that master now does.

2020-10-16 00:41 UTC, hokansom approved these changes
Looking good!

2020-10-16 00:41 UTC, merged