Invitees
Clotonervo/Event-Planner pull request #54
Opened 2020-10-15 23:56 UTC by jam1023

Created invitees component. Takes text (name of invitee) and rsvpStatus (accepted, declined, pending).

2020-10-15 23:57 UTC, jam1023 commented
<img width="737" alt="Screen Shot 2020-10-15 at 5 55 13 PM" src="https://user-images.githubusercontent.com/69694746/96197631-e07ac380-0f0f-11eb-9407-4337a6d2f37e.png">

2020-10-16 00:10 UTC, hokansom commented on client/src/components/Main/Invitee/index.js
> +const Invitee = ({color,text,onClick,rsvpStatus,...props}) => {
For once, I don't think we need an onClick method, so you can get rid of that, as well as color (unless you're using it elsewhere). 

To be more specific, could you change "text" to "name."

2020-10-16 00:11 UTC, hokansom requested changes
You're getting really good at this! Just minor change to remove code we don't need as mentioned in the comments, and you'll be good to go!

2020-10-16 01:08 UTC, jam1023 commented
changed text to name, got rid of onClick, and removed my development lines from Main/index.js

2020-10-16 01:10 UTC, hokansom approved these changes
Perfect 👌

2020-10-16 01:11 UTC, merged